### ISSUE TITLE
Addition of Unbound for DNS provider

### ISSUE THREAD

**Issue by dickiesanders** [alectrocute/wg-api#1]
Currently, you only have options for Cloudflare, Google DNS, and OpenDNS, but with a full tunnel, which is the default setup, and an external DNS, the VPN end-user is leaking traffic every time a DNS request/lookup comes from a client device.

I propose to add a fourth option to install/configure unbound and iptables so that the wireguard server will act as the VPN DNS.

This [guide](https://golb.hplar.ch/2018/10/wireguard-on-amazon-lightsail.html) has an excellent example of a similar setup.

**Comment by alectrocute** [comment]
Definitely a big enhancement for the helper script itself, which is a tiny bit out of the current work scope. Will be saving this for a bit later on. Cheers!

**Comment by alectrocute** [comment]
Are you proposing having a fourth option for `wg.interface:53`?
