### ISSUE TITLE
-4: substring expression < 0

### ISSUE THREAD

**Issue by MasterMB2** [alectrocute/wg-api#2]
![photo_2020-05-20_23-27-56](https://user-images.githubusercontent.com/11151770/82486223-c6b88a00-9af1-11ea-8544-c95b16ae3d8c.jpg)
im getting this error on CentOS 7. please help me out. thanks.

**Comment by MuhammadHasham23** [comment]
Same here on Ubuntu 19.04

**Comment by alectrocute** [comment]
@MasterMB2 @MohammadHasham Unfortunately I can only provide support for Ubuntu, and since it's reported that Ubuntu is affected, let me look into this.

@MohammadHasham Which Node version are you running?

**Comment by stitou-otmane** [comment]
Hello, I have the same error `./installer.sh: line 179: -4: substring expression < 0`, I use : 

- Ubuntu 20.04
- Node : v12.18.2
- NPM : 6.14.5

**Comment by alectrocute** [comment]
Any chance a recent community PR fixed this?

#3 

```js
    CLIENT_ADDRESS="${PRIVATE_SUBNET::-4}$((LASTIP+1))"
```
