### ISSUE TITLE
Is this WireGuad Interface/Peer Configuration persistant ?

### ISSUE THREAD

**Issue by RunsetTech** [alectrocute/wg-api#4]
Hi
Is this script WireGuad Interface/Peer Configuration persistan on service restart ?
and another question is if i have thousand users and i make config for each of them on the fly may this cause interruption of other users ? (since creating and inserting each peer should restart the service to make user be able to connect successfully with that newly created config)

**Comment by alectrocute** [comment]
Yes, it's persistent.
